import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CPUService {
  private registers: any = {
    a: 0x00,
    b: 0x00,
    c: 0x00,
    d: 0x00,
    e: 0x00,
    f: 0x00,
    h: 0x00,
    l: 0x00,
    sp: 0x00,
    pc: 0x00,
  }

  instructions = {
    0x00: () => { return },
    0x01: () => { return },
    0x02: () => { return },
    0x03: () => { return },
    0x04: () => { return },
    0x05: () => { return },
    0x06: () => { return },
    0x07: () => { return },
    0x08: () => { return },
    0x09: () => { return },
    0x0A: () => { return },
    0x0B: () => { return },
    0x0C: () => { return },
    0x0D: () => { return },
    0x0E: () => { return },
    0x0F: () => { return },
    0x10: () => { return },
    0x11: () => { return },
    0x12: () => { return },
    0x13: () => { return },
    0x14: () => { return },
    0x15: () => { return },
    0x16: () => { return },
    0x17: () => { return },
    0x18: () => { return },
    0x19: () => { return },
    0x1A: () => { return },
    0x1B: () => { return },
    0x1C: () => { return },
    0x1D: () => { return },
    0x1E: () => { return },
    0x1F: () => { return },
    0x20: () => { return },
    0x21: () => { return },
    0x22: () => { return },
    0x23: () => { return },
    0x24: () => { return },
    0x25: () => { return },
    0x26: () => { return },
    0x27: () => { return },
    0x28: () => { return },
    0x29: () => { return },
    0x2A: () => { return },
    0x2B: () => { return },
    0x2C: () => { return },
    0x2D: () => { return },
    0x2E: () => { return },
    0x2F: () => { return },
    0x30: () => { return },
    0x31: () => { return },
    0x32: () => { return },
    0x33: () => { return },
    0x34: () => { return },
    0x35: () => { return },
    0x36: () => { return },
    0x37: () => { return },
    0x38: () => { return },
    0x39: () => { return },
    0x3A: () => { return },
    0x3B: () => { return },
    0x3C: () => { return },
    0x3D: () => { return },
    0x3E: () => { return },
    0x3F: () => { return },
    0x40: () => { return },
    0x41: () => { return },
    0x42: () => { return },
    0x43: () => { return },
    0x44: () => { return },
    0x45: () => { return },
    0x46: () => { return },
    0x47: () => { return },
    0x48: () => { return },
    0x49: () => { return },
    0x4A: () => { return },
    0x4B: () => { return },
    0x4C: () => { return },
    0x4D: () => { return },
    0x4E: () => { return },
    0x4F: () => { return },
    0x50: () => { return },
    0x51: () => { return },
    0x52: () => { return },
    0x53: () => { return },
    0x54: () => { return },
    0x55: () => { return },
    0x56: () => { return },
    0x57: () => { return },
    0x58: () => { return },
    0x59: () => { return },
    0x5A: () => { return },
    0x5B: () => { return },
    0x5C: () => { return },
    0x5D: () => { return },
    0x5E: () => { return },
    0x5F: () => { return },
    0x60: () => { return },
    0x61: () => { return },
    0x62: () => { return },
    0x63: () => { return },
    0x64: () => { return },
    0x65: () => { return },
    0x66: () => { return },
    0x67: () => { return },
    0x68: () => { return },
    0x69: () => { return },
    0x6A: () => { return },
    0x6B: () => { return },
    0x6C: () => { return },
    0x6D: () => { return },
    0x6E: () => { return },
    0x6F: () => { return },
    0x70: () => { return },
    0x71: () => { return },
    0x72: () => { return },
    0x73: () => { return },
    0x74: () => { return },
    0x75: () => { return },
    0x76: () => { return },
    0x77: () => { return },
    0x78: () => { return },
    0x79: () => { return },
    0x7A: () => { return },
    0x7B: () => { return },
    0x7C: () => { return },
    0x7D: () => { return },
    0x7E: () => { return },
    0x7F: () => { return },
    0x80: () => { return },
    0x81: () => { return },
    0x82: () => { return },
    0x83: () => { return },
    0x84: () => { return },
    0x85: () => { return },
    0x86: () => { return },
    0x87: () => { return },
    0x88: () => { return },
    0x89: () => { return },
    0x8A: () => { return },
    0x8B: () => { return },
    0x8C: () => { return },
    0x8D: () => { return },
    0x8E: () => { return },
    0x8F: () => { return },
    0x90: () => { return },
    0x91: () => { return },
    0x92: () => { return },
    0x93: () => { return },
    0x94: () => { return },
    0x95: () => { return },
    0x96: () => { return },
    0x97: () => { return },
    0x98: () => { return },
    0x99: () => { return },
    0x9A: () => { return },
    0x9B: () => { return },
    0x9C: () => { return },
    0x9D: () => { return },
    0x9E: () => { return },
    0x9F: () => { return },
    0xA0: () => { return },
    0xA1: () => { return },
    0xA2: () => { return },
    0xA3: () => { return },
    0xA4: () => { return },
    0xA5: () => { return },
    0xA6: () => { return },
    0xA7: () => { return },
    0xA8: () => { return },
    0xA9: () => { return },
    0xAA: () => { return },
    0xAB: () => { return },
    0xAC: () => { return },
    0xAD: () => { return },
    0xAE: () => { return },
    0xAF: () => { return },
    0xB0: () => { return },
    0xB1: () => { return },
    0xB2: () => { return },
    0xB3: () => { return },
    0xB4: () => { return },
    0xB5: () => { return },
    0xB6: () => { return },
    0xB7: () => { return },
    0xB8: () => { return },
    0xB9: () => { return },
    0xBA: () => { return },
    0xBB: () => { return },
    0xBC: () => { return },
    0xBD: () => { return },
    0xBE: () => { return },
    0xBF: () => { return },
    0xC0: () => { return },
    0xC1: () => { return },
    0xC2: () => { return },
    0xC3: () => { return },
    0xC4: () => { return },
    0xC5: () => { return },
    0xC6: () => { return },
    0xC7: () => { return },
    0xC8: () => { return },
    0xC9: () => { return },
    0xCA: () => { return },
    0xCB: () => { return },
    0xCC: () => { return },
    0xCD: () => { return },
    0xCE: () => { return },
    0xCF: () => { return },
    0xD0: () => { return },
    0xD1: () => { return },
    0xD2: () => { return },
    0xD3: () => { return },
    0xD4: () => { return },
    0xD5: () => { return },
    0xD6: () => { return },
    0xD7: () => { return },
    0xD8: () => { return },
    0xD9: () => { return },
    0xDA: () => { return },
    0xDB: () => { return },
    0xDC: () => { return },
    0xDD: () => { return },
    0xDE: () => { return },
    0xDF: () => { return },
    0xE0: () => { return },
    0xE1: () => { return },
    0xE2: () => { return },
    0xE3: () => { return },
    0xE4: () => { return },
    0xE5: () => { return },
    0xE6: () => { return },
    0xE7: () => { return },
    0xE8: () => { return },
    0xE9: () => { return },
    0xEA: () => { return },
    0xEB: () => { return },
    0xEC: () => { return },
    0xED: () => { return },
    0xEE: () => { return },
    0xEF: () => { return },
    0xF0: () => { return },
    0xF1: () => { return },
    0xF2: () => { return },
    0xF3: () => { return },
    0xF4: () => { return },
    0xF5: () => { return },
    0xF6: () => { return },
    0xF7: () => { return },
    0xF8: () => { return },
    0xF9: () => { return },
    0xFA: () => { return },
    0xFB: () => { return },
    0xFC: () => { return },
    0xFD: () => { return },
    0xFE: () => { return },
    0xFF: () => { return }
  }
  constructor() { }

  writeRegister(register: string, value: number) {
    this.registers[register] = value;
  }

  readRegister(register: string): number {
    return this.registers[register];
  }
}
